config/routes.rb
Rails.application.routes.draw do
  telegram_webhook Telegram::WebhookController

  get '/', to: 'welcome#welcome'
  resources :feedbacks, only: %i(index show) do
    member do
      post :reply
    end

    collection do
      get :closed
    end
  end
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  include FeedbackPresenter

  validates :text, presence: true
  belongs_to :authentication
  enum state: { opened: 0, closed: 1 }
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :feedback, only: %i[show reply]

  def index
    @feedbacks = Feedback.opened.includes(:authentication).order(id: :desc).limit 100
  end

  def show; end

  def reply
    Feedbacks::Reply.call @feedback, answer: params[:answer]
    redirect_to feedbacks_path
  rescue Feedbacks::Reply::Error
    redirect_to @feedback
  end

  def closed
    @feedbacks = Feedback.closed.includes(:authentication).order(id: :desc).limit 100
  end

  private

  def feedback
    @feedback ||= Feedback.find params[:id]
  end
end

app/controllers/telegram/feedbacks_controller.rb
module Telegram
  class FeedbacksController < ApplicationController
    def callback_query(data)
      callback_strategy(data.to_sym)&.call
    end

    def message(message)
      action = global_session[:last_action]&.dig(:args)&.first
      return unless action
      return if global_session[:last_action][:action] != 'callback_query'

      action_name, _options = parse_action(action)
      last_action_strategy(action_name.to_sym)&.call message['text']
    end

    private

    def callback_strategy(action)
      {
        feedback: -> { Feedbacks::NewAnswer.render self }
      }[action]
    end

    def last_action_strategy(action)
      {
        feedback: ->(message) { create_feedback(message) }
      }[action]
    end

    def create_feedback(message)
      ::Feedbacks::Create.call authentication: current_authentication, text: message
      Feedbacks::CreatedAnswer.render self
    rescue ::Feedbacks::Create::Error
      Feedbacks::ErrorAnswer.render self
    end
  end
end

app/views/feedbacks/closed.html.erb
<table>
  <thead>
    <tr>
      <th><%= t('feedback.user') %></th>
      <th><%= t('feedback.from') %></th>
      <th><%= t('feedback.text') %></th>
      <th><%= t('feedback.answer') %></th>
    </tr>
  </thead>

  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= feedback.authentication_title %></td>
        <td><%= feedback.authentication_provider %></td>
        <td><%= feedback.text %></td>
        <td><%= feedback.answer %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/feedbacks/index.html.erb
<table>
  <thead>
    <tr>
      <th></th>
      <th><%= t('feedback.user') %></th>
      <th><%= t('feedback.from') %></th>
      <th><%= t('feedback.text') %></th>
    </tr>
  </thead>

  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= link_to t('feedback.respond'), feedback_path(feedback) %></td>
        <td><%= feedback.authentication_title %></td>
        <td><%= feedback.authentication_provider %></td>
        <td><%= feedback.preview %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/feedbacks/show.html.erb
<p><%= @feedback.authentication_title %></p>
<p><%= @feedback.authentication_provider %></p>
<p><%= @feedback.text %></p>

<%= form_with url: reply_feedback_path(@feedback), method: :post, local: true do |form| %>
  <%= form.text_area :answer %>
  <%= form.submit t('feedback.submit') %>
<% end %>